### ISSUE TITLE
Unprintable ASCII character found in Swift Source Code

### ISSUE THREAD

**Issue by NicoMulet** [SwiftGen/SwiftGen#985]
Environment:
- SwiftGen 6.6.1
- Xcode 13.4
- Targeting iOS 15+

With the latest Swiftgen version, `\t` contained inside a localised string are incorrectly converted into a non ASCII character.

For instance:
```strings
"a_string_with_a_tab" = "A string with a tab\t";
```
Will result in the `strings.generated.swift` file as so:
```swift
internal static let aStringWithATab = L10n.tr("Localizable", "a_string_with_a_tab", fallback: "A string with a tab	")
```
Instead of:
```swift
internal static let aStringWithATab = L10n.tr("Localizable", "a_string_with_a_tab", fallback: "A string with a tab\t")
```

Here is the result with Xcode 13.4:
<img width="1293" alt="Screenshot 2022-08-01 at 11 02 33" src="https://user-images.githubusercontent.com/22772021/182113244-2485a60a-cf32-467d-b0fd-4ef93077ecf3.png">

**Comment by djbe** [comment]
That's honestly annoying of Xcode… It's a tab, how is that invalid?

**Comment by djbe** [comment]
Fixed in 6.6.2

**Comment by vkcldhkd** [comment]
I used 6.6.2, but it still occurs

Here is the result with Xcode 15.0:
![스크린샷 2023-10-10 오전 11 38 25](https://github.com/SwiftGen/SwiftGen/assets/6158125/f79275d3-bca8-48df-aed9-42e518fcc845)



Here is the result with VSCode:
![스크린샷 2023-10-10 오전 11 26 55](https://github.com/SwiftGen/SwiftGen/assets/6158125/850ca37a-a5b4-451d-8d79-17d7f2007a4d)
